---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Páginas especiales
- type: document
  path: data/es/homepage.yml
  label: Homepage
- type: document
  path: data/es/about.yml
  label: Sobre nosotros
- type: document
  path: config.toml
  label: Configuración
- type: document
  path: data/es/services.yml
  label: Widget Servicios
- type: heading
  label: Contenido
- type: directory
  path: content/es/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content/es
  label: Español
  create: all
  match: "**/*"
  templates:
  - autor
  - blog-post
  - miembro-de-equipo
  - proyecto
  - servicio
- type: directory
  path: content/es/service
  label: Servicios
  create: all
  match: "**/*"
  templates:
  - servicio
- type: directory
  path: content/es/project
  label: Proyectos
  create: all
  match: "**/*"
  templates:
  - proyecto
- type: directory
  path: content/es/docencia
  label: Docencia
  create: all
  match: "**/*"
  templates:
  - servicio
- type: directory
  path: content/es/team
  label: Miembros del equipo
  create: all
  match: "**/*"
  templates:
  - miembro-de-equipo
- type: directory
  path: content/es/author
  label: Autor
  create: all
  match: "**/*"
  templates:
  - autor
- type: directory
  path: content/es/contact
  label: Contacto
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/images
public_path: "/images"
front_matter_path: "/images"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.69.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.69.0
